import pandas as pd
from tqdm import tqdm


"""
This script parses the output from the hmmscan --domtblout search, calculates the coverage for each hit with 
respect to the HMM profile, and returns a .csv file with the processed results (OUTPUT1). A second output (OUTPUT2) 
is generated by filtering the hits based on the given coverage threshold. 
"""


# output domtblout hmmscan search
file1 = ""
# THRESHOLD COVERAGE
THRESHOLD_COV = 50
# evalue
EVALUE = "001"

# Name for output files
OUTPUT1 = f"Output_domtblout_processed_{EVALUE}_coverage.csv"
OUTPUT2 = f"Output_domtblout_processed_{EVALUE}_{THRESHOLD_COV}cov.csv"


##### Parse domblout file and create dataframe #####
def parse_domblout(filename):
    list_aux=[]
    with open (filename, "r") as f:
        rdr=iter(f)
        for line in rdr:
            if line.startswith("#"):
                continue
            aux=line.split()
            dicc={
                "Target_name" : aux[0],
                "Profile_accession" : aux[1],
                "tlen" : aux[2],
                "Query_name": aux[3],
                "Accession" : aux[4],
                "qlen" : aux[5],
                "E-value": aux[6],
                "score": aux[7], 
                "bias": aux[8], 
                "#": aux[9], 
                "of": aux[10],
                "e-Evalue" : aux[11],
                "i-Evalue": aux[12],
                "score_D": aux[13],
                "bias_D": aux[14],
                "hmm_from" : aux[15],
                "hmm_to" : aux[16],
                "ali_from" : aux[17],
                "ali_to": aux[18],
                "env_from" : aux[19],
                "env_to" : aux[20],
                "acc" : aux[21],
                "Description_target" : " ".join(aux[22:])
            }
            list_aux.append(dicc)
    df=pd.DataFrame(list_aux)
    return df

# create dataframe
df=parse_domblout(file1)


# CALCULATE PROFILE COVERAGE FOR EACH HIT
def calculate_cov(row):
    start = int(row["hmm_from"])
    end = int(row["hmm_to"])
    total = int(row["tlen"])
    cov = (end - start + 1)*100/total
    return cov

tqdm.pandas(desc="my bar!")
df["Coverage_hmm"]=df.progress_apply(calculate_cov, axis=1)
df.to_csv(OUTPUT1, sep=",")

# Filter hits by coverage threshold
df_filt = df[df["Coverage_hmm"]>=THRESHOLD_COV]
df_filt.to_csv(OUTPUT2, sep=",")
proteins_cov = df_filt["Query_name"].to_list()
print(f"Total hits with >={THRESHOLD_COV} cov profile: ", len(proteins_cov), len(set(proteins_cov)))






